# ===========================  mbi Configuration template for mimxrt685s, Revision: latest.  ===========================

# ======================================================================================================================
#                                                 == General Options ==
# ======================================================================================================================
# -------------------------------------===== The chip family name [Required] =====--------------------------------------
# Description: NXP chip family identifier.
family: mimxrt685s
# -----------------------------------------===== MCU revision [Optional] =====------------------------------------------
# Description: Revision of silicon. The 'latest' name, means most current revision.
# Possible options: <a0, b0, latest>
revision: latest
# ======================================================================================================================
#                                                  == Basic Settings ==
# ======================================================================================================================
# --------------------------------------===== Application target [Required] =====---------------------------------------
# Description: Definition if application is Execute in Place(XiP) or loaded to RAM during reset sequence.
# Possible options: <xip, load-to-ram>
outputImageExecutionTarget: xip
# -------------------------------===== Type of boot image authentication [Required] =====-------------------------------
# Description: Specification of final master boot image authentication.
# Possible options: <signed, plain, crc, signed-encrypted>
outputImageAuthenticationType: signed
# ---------------------------------------===== Output Image name [Required] =====---------------------------------------
# Description: The path for result binary file.
masterBootOutputFile: placeholder # filled in by tooling
# ------------------------------------===== Plain application image [Required] =====------------------------------------
# Description: The input application image to by modified to Master Boot Image.
inputImageFile: placeholder # filled in by tooling
# --------------------------------===== The list of additional binaries [Optional] =====--------------------------------
# Description: This is software feature of RTxxx family that NXP SDK startup code (not ROM) could load additional
# images.
# applicationTable:
# - # ----------------------------------------===== Binary file [Required] =====----------------------------------------
#   # Description: The binary file to be added to final application.
#   binary: my_additional_binary.bin
#   # ------------------------------------===== Destination address [Required] =====------------------------------------
#   # Description: Destination address in RAM of additional binary.
#   destAddress: 536870912
#   # ----------------------------------------===== Enable load [Required] =====----------------------------------------
#   # Description: Enabler to load/use the image.
#   load: true
# --------------------------------===== Loading address of application [Optional] =====---------------------------------
# Description: Application loading address in RAM if not XiP, otherwise address of load in XiP.
outputImageExecutionAddress: 0 # filled in by tooling
# ----------------------------------===== Enable User HW key sharing [Required] =====-----------------------------------
# Description: Controlling secure hardware key bus. If enabled(1), then it is possible to access keys on hardware secure
# bus from non-secure application, else non-secure application will read zeros.
enableHwUserModeKeys: false
# ======================================================================================================================
#                                               == Trust Zone Settings ==
# ======================================================================================================================
# ------------------------------------===== TrustZone enable option [Optional] =====------------------------------------
# Description: If not specified, the Trust zone is disabled.
enableTrustZone: true
# ---------------------------------===== TrustZone Customization file [Optional] =====----------------------------------
# Description: If not specified, but TrustZone is enabled(enableTrustZone) the default values are used.
#trustZonePresetFile: my_tz_custom.yaml
# ======================================================================================================================
#                                               == Certificate Block V1 ==
# ======================================================================================================================
# -----------------------------===== Certificate Block binary/config file [Required] =====------------------------------
# Description: Path to certificate block binary or config file.
certBlock: placeholder # filled in by tooling
# ======================================================================================================================
#                                              == Image Signing Settings ==
# ======================================================================================================================
# -------------------------------------===== Signer configuration [Required] =====--------------------------------------
# Description: Signature provider configuration in format 'type=<sp_type>;<key1>=<value1>;<key2>=<value2>' or path to a
# private key.
signer: type=file;file_path=cert-img2-user-key.pem
# ======================================================================================================================
#                                               == Encryption Settings ==
# ======================================================================================================================
# -----------------------------------===== OTP Master key (HMAC Key) [Required] =====-----------------------------------
# Description: The OTP Master key that is used to compute HMAC encryption key. Could be defined as hex number and also
# as hex/binary file.\n Used algorithm by tool the get HMAC Key; AES_ENCRYPT (OTP_MASTER_KEK,
# 0x00000000000000000000000000000000)
# outputImageEncryptionKeyFile: otp_master_key.txt
# ------------------------------------===== The Key store data file [Optional] =====------------------------------------
# Description: Optional KeyStore data file for included keystore in LoadToRam images. If defined the KeyStore is added
# into MBI.
# keyStoreFile: my_key_store_data.bin
